version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install boto3 scikit-learn pandas joblib

  pre_build:
    commands:
      - echo "Starting training pipeline..."

  build:
    commands:
      - python train/train.py

  post_build:
    commands:
      - echo "Training complete!"